[project]
name = "wagyu-ai"
version = "0.1.0"
description = "GBSW 2nd-semester Capstone AI Project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "trl",
    "peft",
    "transformers",
    "bitsandbytes",
    "datasets",
    "konlpy",
    "torch",
]
